# Generated by Django 5.0.6 on 2024-07-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blur', '0003_rename_identication_cni_ident_cni_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cni',
            old_name='ident',
            new_name='NumeroCni',
        ),
    ]
