# Generated by Django 5.0.6 on 2024-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blur', '0004_rename_ident_cni_numerocni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cni',
            name='date',
        ),
        migrations.AddField(
            model_name='cni',
            name='addresse',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='cni',
            name='date_naissance',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='cni',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cni',
            name='prenom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cni',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cni',
            name='sexe',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cni',
            name='NumeroCni',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cni',
            name='nom',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
