# Generated by Django 5.0.6 on 2024-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blur', '0005_remove_cni_date_cni_addresse_cni_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cni',
            name='NumeroCni',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cni',
            name='lieu_naissance',
            field=models.CharField(default='Inconnu', max_length=20),
        ),
        migrations.AlterField(
            model_name='cni',
            name='nom',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cni',
            name='prenom',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cni',
            name='profession',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cni',
            name='sexe',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
